name: SouthPlus签到

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Chrome
      run: |
        CHROME_VERSION=106.0.5249.21
        wget https://www.slimjet.com/chrome/download-chrome.php?file=files%2F103.0.5060.53%2Fgoogle-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/103.0.5060.53/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/

    - name: 总脚本
      env:
        COOKIE: ${{ secrets.COOKIE }}
      run: python byWebdriver.py
