name: SouthPlus签到

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 17 * * *' 

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          install-chromedriver: true

      - name: 总脚本
        env:
          COOKIE: ${{ secrets.COOKIE }}
          serverKey: ${{ secrets.serverKey }}
        run: python byWebdrvier.py
